### ISSUE TITLE
Generated PDF/PNG are Broken But DOT Format Works

### ISSUE THREAD

**Issue by pacarvalho** [voormedia/rails-erd#355]
Whenever I opt for a format that is not DOT such as PDF and PNG I end up with something that looks like the image below:

![erd](https://user-images.githubusercontent.com/860599/84190915-b008b180-aa65-11ea-91ee-2da242594330.png)

I am running my code with the following Dockerfile:

```Dockerfile
FROM ruby:2.5-alpine AS installer

# Expose port
EXPOSE 3000

# set some rails env vars
ENV RAILS_ENV production
ENV PORT 3000

# set the app directory var
ENV APP_HOME /app
RUN mkdir -p ${APP_HOME}
WORKDIR ${APP_HOME}

# Install necessary packanges
RUN apk add --no-cache \
    build-base curl libressl-dev zlib-dev git \
    mariadb-dev tzdata imagemagick libxslt-dev \
    bash nodejs graphviz

# Copy gemfiles to be able to bundle install
COPY Gemfile* ./
```

Using the ERD configuration below:

```yaml
attributes:
  - content
  - foreign_key
  - inheritance
disconnected: true
filename: erd
filetype: png
indirect: true
inheritance: false
markup: true
notation: simple
orientation: horizontal
polymorphism: false
sort: true
warn: true
title: sample title
exclude: null
only: null
only_recursion_depth: null
prepend_primary: false
cluster: false
splines: spline
```

And running the command `bundle exec erd` inside the running container. The DOT format works as expected. Any ideas what could be causing this?

**Comment by johnsaltarelli** [comment]
@pacarvalho I was experiencing the same issue. The core of the problem is that the font specified by the RailsERD gem is "Arial" and this font is not available within the ruby Alpine image being used in your Dockerfile. Additionally, you cannot override this font through the standard RailsERD config options. 

There is a way to install Arial into the Ruby Alpine Docker image. However, I have not been able to get this to work using the `msttcorefonts-installer` Alpine package (suggested by numerous SO questions). Because of this, I opted to install an alternate font into Alpine and then configure RailsERD to use this font instead. 

I solved this by monkey patching the RailsERD gem via an initializer. I override the method returning the Arial font names. I opted to installed the NOTO font package (I believe any font would work). 

Dockerfile
```

# Install Graphviz & Fonts
RUN apk add graphviz
RUN apk add font-noto
RUN apk add fontconfig 
RUN fc-cache -f

```
./config/initalizers/rails_erd.rb
```

module RailsERD
    class Config
        def self.font_names_based_on_os
            { 
                normal: "Noto Sans",
                bold:   "Noto Sans Bold",
                italic: "Noto Sans Italic",
            }
        end
    end
end

``` 

I am running 6.1.3 and was able to successfully generate a PDF diagram using this method.

**Comment by kerrizor** [comment]
>  It would be great if we could pass in font names when generating diagrams or as a YAML configuration option in .erdconfig

I don't see why we couldn't add that!

**Comment by kerrizor** [comment]
Hey @pacarvalho! 👋

This issue is caused by missing fonts in Alpine Linux. As @johnsaltarelli explained, the gem defaults to Arial which isn't available in Alpine.

**Good news:** The gem now supports custom fonts via the `.erdconfig` file! You can set:

```yaml
fonts:
  normal: "Noto Sans"
  bold: "Noto Sans Bold"
  italic: "Noto Sans Italic"
```

Combined with installing fonts in your Dockerfile:
```dockerfile
RUN apk add font-noto fontconfig && fc-cache -f
```

This should resolve the issue without needing to monkey-patch. Closing as the workaround is now a supported feature! 🙏
